### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by xiehaiy** [dparks1134/GenomeTreeTk#1]
I have seen many articles citing your software, but I know how to use it? Can you send a description document? The more detailed, the better. I am a newer. Thank you very much!

**Comment by donovan-h-parks** [comment]
Hello. If you are referring to the GTDB and want to classify genomes using this taxonomy, take a look at the GTDB-Tk:
https://github.com/Ecogenomics/GTDBTk

The taxonomy itself is at:
http://gtdb.ecogenomic.org/

Cheers,
Donovan

**Comment by xiehaiy** [comment]
Thank you for your answer. If I want to remove some species when construct genome tree phylogeny, what can I do? 

Cheers,
Xiehaiying
