### ISSUE TITLE
How to use the phylogenetic_diversity.py

### ISSUE THREAD

**Issue by CodeFeiX** [dparks1134/GenomeTreeTk#2]
I was confused that one of the scripts had no instructions, and actually found it so useful.  So I hope to get the answer from the author of this software.

**Comment by donovan-h-parks** [comment]
GenomeTreeTk and associated scripts are not recommended for public use. The code is provided for those wishing to investigate it, but we do not currently have the resources to document and maintain this software package. Sorry I can't be of direct help.

**Comment by xiefeinjau** [comment]
In fact, I wish to invite you to join us. I have some microbial genome data and I need this index (phylogenetic diversity/phylogenetic gain) to show its  value.


| |
Fei Xie
Nanjing Agricultural University
|
|
College of Animal Science and Technology
xiefei_njau@163.com
|
签名由网易邮箱大师定制
On 10/25/2019 22:20，Donovan Parks<notifications@github.com> wrote：

GenomeTreeTk and associated scripts are not recommended for public use. The code is provided for those wishing to investigate it, but we do not currently have the resources to document and maintain this software package. Sorry I can't be of direct help.

**Comment by donovan-h-parks** [comment]
Hi. Have you tried to run this script via the GenomeTreeTk command line interface:
>genometreetk pd -h

For most uses, it simply requires an input tree in Newick format and a plain text file listing the genomes you wish to calculate PD for.

**Comment by CodeFeiX** [comment]
yeah，but i don't know the input data and parameters




| |
Fei Xie
Nanjing Agricultural University
|
|
College of Animal Science and Technology
xiefei_njau@163.com
|

Signature is customized by Netease Mail Master

On 10/25/2019 22:32, Donovan Parks wrote:

Hi. Have you tried to run this script via the GenomeTreeTk command line interface:

genometreetk pd -h

For most uses, it simply requires an input tree in Newick format and a plain text file listing the genomes you wish to calculate PD for.

**Comment by donovan-h-parks** [comment]
Addressed via personal communication with toy example:

>genometreetk pd my_tree.tre my_taxa.lst

my_tree.tree: is a phylogenetic tree in Newick format
my_taxa.lst: is a plain text file with one taxa per line

Example tree: ((a:1,b:1):2,c:2);
Example taxa file:
a
c

This calculates the phylogenetic diversity spanned by taxa a and c. The output is:

No. Taxa        PD      Percent PD
Full tree       3       6.00    100.00%
Outgroup taxa (PD)      1       3.00    50.000%
Ingroup taxa (PD)       2       5.00    83.333%
Ingroup taxa (PG)       2       3.00    50.000%

This indicates the full tree has a branch length of 6 and that the two taxa a and c have a branch length of 5 which is 83.3% of the total. These two taxa add a total branch length (i.e. phylgenetic gain) of 3 which is 50%.
